# Timeouts (in seconds)
HEARTBEAT_TIMEOUT = 1020 # 17 minutes

# Colors
COLOR_RED = 'red'
COLOR_AMBER = 'amber'
COLOR_GREEN = 'green'

# Location Types
LOCATION_TYPE_HUB = 'HUB'
LOCATION_TYPE_WARD = 'WARD'
LOCATION_TYPE_REMOTE = 'REMOTE'

# Vial Status
STATUS_AVAILABLE = 'AVAILABLE'
STATUS_IN_TRANSIT = 'IN_TRANSIT'
STATUS_USED_CLINICAL = 'USED_CLINICAL'
STATUS_DISCARDED = 'DISCARDED'
STATUS_EXPIRED = 'EXPIRED' # If used logic
